pipeline {
        agent any
        environment {
            DOCKERHUB_CREDENTIALS = credentials('dockerhub-cred-may')
            resultImage = ''
            voteImage = ''
            workerImage = ''
	    }  
    stages { 
            stage('Clone repo') {
                steps{
                    checkout([$class: 'GitSCM', branches: [[name: '*/main']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/may-meriem/voting-app-example.git']]])	
                }
            }
            stage('Build result') {
                steps{
                    resultImage = docker.build("ibuchh/examplevotingapp-result", "./result")
                }
            }
            stage('Build vote') {
                steps{
                    voteImage = docker.build("ibuchh/examplevotingapp-vote", "./vote")
                }
            }
            stage('Build worker dotnet') {
                steps{
                    workerImage = docker.build("ibuchh/examplevotingapp-worker", "./worker")
                }
            }
            stage('Push result image') {
                steps{
                    resultImage.push("${env.BUILD_NUMBER}")
                    resultImage.push()
                }
            }
            stage('Push vote image') {
                steps{
                    voteImage.push("${env.BUILD_NUMBER}")
                    voteImage.push()
                }
            }
            stage('Push worker image') {
                steps{
                    workerImage.push("${env.BUILD_NUMBER}")
                    workerImage.push()
                }
            }
    }
}
